version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.3
    depends_on:
      - elasticsearch
    ports:
      - "5043:5043"
      - "5044:5044"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: changeme
    ports:
      - "5601:5601"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: http://elasticsearch:9200
      ES_USERNAME: elastic
      ES_PASSWORD: changeme